hidden-segns:
- west_american_sea
- east_american_sea
- south_european_sea
- north_european_sea
- west_african_sea
- east_african_sea
- indian_pacific_sea
- north_pacific_sea
path:
    area: ""
    locl: ""
    regn: ""
    segn: ""
rem-from-repr:
- modifiers
- filename
- discovered
repr-font-size: 10
was-configured: false
hide-listed-segn: true
hide-no-segn: true
