path:
  area: D:/Games/Europa-Universalis-IV/mod/disk_mod/map/area.txt
  locl: D:/Games/Europa-Universalis-IV/mod/disk_mod/localisation/prov_names_l_english.yml
  regn: D:/Games/Europa-Universalis-IV/mod/disk_mod/map/region.txt
  segn: D:/Games/Europa-Universalis-IV/mod/disk_mod/map/superregion.txt
was-configured: true
