################################
# Editor Core Configuration
################################

# Files
path:
    map-def: /map/default.map
    color-def: /map/definition.csv
    prov-map: /map/provinces.bmp
    prov-names: /localisation/prov_names_l_$LANG$.yml
    area-assign: /map/area.txt
    regn-assign: /map/region.txt
    segn-assign: /map/superregion.txt
    prov-hist-dir: /history/provinces/

encodings-list: [
    utf-8-sig, utf-8, ansi
]

# Images scaling
scale-step: 1.1 # fraction in range 1 - 2
scale-ignore: 0.03 # if abs(1-scale) is less than this, scale will be set to 1
scale-max: 1.8
scale-min: 0.3

# Interface
scroll-step: 3
scroll-start: [44, 8] # NW corner of visible (% of whole map)
btt-width: 80
btt-height: 27

default-date: [1444, 11, 11]

# History data
bln-fkeys: # Boolean values
    is_city: city
    hre: HRE
    seat_in_parliament: parl_seat

spc-fkeys: # Specific values
    capital: capital
    owner: owner
    trade_goods: tr_goods
    latent_trade_goods: latent_trg
    controller: cntrl
    culture: culture
    religion: religion
    estate: estate
    reformation_center: reform_cntr
    revolt: revolt

num-fkeys: # Numeric values
    add_local_autonomy: autonomy
    extra_cost: cost
    unrest: unrest
    revolt_risk: rvlt_risk
    base_tax: tax
    base_production: prod
    base_manpower: manpower
    manpower: manpower # there is only 1 entry, it's probably a mistake
    native_hostileness: ntv_hstl
    native_ferocity: ntv_ferc
    native_size: ntv_size

add-fkeys: # Can have multiple values (add command)
    add_core: core
    add_claim: claim
    discovered_by: discovered
    add_permanent_province_modifier: perm_mdf
    add_province_triggered_modifier: trig_mdf

rem-fkeys: # (remove command)
    remove_core: core
    remove_claim: claim
    remove_province_modifier: perm_mdf

bld-fkeys: # Buildings
    trade: [marketplace, trade_depot, stock_exchange]
    sailors: [dock, drydock]
    navy: [shipyard, grand_shipyard]
    manpower: [barracks, training_fields]
    army: [regimental_camp, conscription_center]
    defense: [fort_15th, fort_16th, fort_17th, fort_18th]
    government: [courthouse, town_hall]
    university: [university]
    production: [workshop, counting_house]
    taxation: [temple, cathedral]
    manufacturies: [wharf, weapons, textile, plantations, tradecompany,
        farm_estate, mills, furnace]
