################################
# Editor Localisation
################################

#### GENERAL #####
frame-title: 'EGE2'

#### SIDE-BAR #####
# View
lbl-view: 'View'
scale-inc: 'Zoom in'
scale-dec: 'Zoom out'
scale-rst: 'Zoom reset'
# Mapmodes
lbl-mapmodes: 'Map modes'
mm-provs: 'Provinces'
mm-areas: 'Areas'
mm-regns: 'Regions'
mm-segns: 'Super-regions'
mm-cust: 'Custom'
# Selection
lbl-selection: 'Selection'
unmark: 'Unmark all'

#### DIALOGS ####
# Busy Dialog Messages
msg-loading: 'Loading'
msg-loading-data: 'Loading data'
msg-loading-hist: 'Loading history'
msg-loading-map: 'Preparing map'
# Mapmode Choice Dialog
dlg-mapmode-cpt: 'Choose map-mode'
dlg-mapmode-msg: 'Select new map mode'
